name: Run General Assembly Membe Test Cases

on:
  push:
    branches: ["master"]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: "11"
          cache: maven
          distribution: "temurin"
      - uses: browser-actions/setup-chrome@latest
      - run: mvn clean test
